"""Generate a ``scripts/replay.py`` from a Recording.

Surface-aware: browser recordings emit a Playwright Python script, desktop
recordings emit a pyautogui script. The output is intentionally small and
readable — the user is expected to inspect and edit it before running, and
Claude can read it as one more piece of context when executing the skill.

We do not run the script ourselves; we only emit it. Running it requires
``pip install playwright`` (+ ``python -m playwright install chromium``) for
browser recordings, or ``pip install pyautogui`` for desktop.
"""

from __future__ import annotations

import json
from typing import Any

from csrsb.schema import Event, Recording


def generate_replay_script(recording: Recording) -> str:
    """Return the Python source of a replay script for ``recording``."""
    if recording.surface == "browser":
        return _generate_browser_script(recording)
    return _generate_desktop_script(recording)


def _generate_browser_script(recording: Recording) -> str:
    """Emit a Playwright sync API script."""
    lines: list[str] = [
        '"""Auto-generated by csrsb. Best-effort deterministic replay.',
        "",
        "Run with:",
        "    pip install playwright",
        "    python -m playwright install chromium",
        "    python replay.py",
        "",
        "This script replays the recorded actions verbatim using whichever",
        "selector ranked highest at recording time. Inspect and edit before",
        "running against a real environment — selectors do drift.",
        '"""',
        "",
        "from playwright.sync_api import sync_playwright",
        "",
        "",
        "def main() -> None:",
        "    with sync_playwright() as p:",
        "        browser = p.chromium.launch(headless=False)",
        "        context = browser.new_context()",
        "        page = context.new_page()",
        "",
    ]
    last_url: str | None = None
    for event in recording.events:
        line = _browser_event_line(event, last_url)
        if line is None:
            continue
        lines.append(f"        {line}")
        if event.target.url:
            last_url = event.target.url
    lines.extend(
        [
            "",
            "        input('Replay finished — press Enter to close')",
            "        context.close()",
            "        browser.close()",
            "",
            "",
            'if __name__ == "__main__":',
            "    main()",
            "",
        ]
    )
    return "\n".join(lines)


def _browser_event_line(event: Event, last_url: str | None) -> str | None:
    """Map one browser event onto a single Playwright statement.

    Returns ``None`` for events that have no Playwright equivalent (annotations,
    clipboard markers, screen_changed) — those are emitted as comments by the
    caller for traceability.
    """
    selector = _best_selector(event)
    if event.type == "navigate" and event.target.url and event.target.url != last_url:
        return f"page.goto({json.dumps(event.target.url)})"
    if event.type == "click":
        if selector:
            return f"page.locator({json.dumps(selector)}).click()"
        return f"# click at unknown selector ({event.id})"
    if event.type == "input" and selector:
        return f"page.locator({json.dumps(selector)}).fill({json.dumps(str(event.value))})"
    if event.type == "key" and isinstance(event.value, dict):
        key = event.value.get("key", "")
        if key:
            return f"page.keyboard.press({json.dumps(key)})"
    if event.type == "scroll" and isinstance(event.value, dict):
        x, y = event.value.get("x", 0), event.value.get("y", 0)
        return f"page.evaluate('window.scrollTo({x}, {y})')"
    if event.type == "drop" and selector:
        return f"# drop on {selector!r} — Playwright drag_to handled separately ({event.id})"
    return f"# unhandled event: {event.type} ({event.id})"


def _generate_desktop_script(recording: Recording) -> str:
    """Emit a pyautogui script that replays clicks + typed input."""
    lines: list[str] = [
        '"""Auto-generated by csrsb. Best-effort deterministic replay.',
        "",
        "Run with:",
        "    pip install pyautogui",
        "    python replay.py",
        "",
        "Replays the recorded clicks and keystrokes at the recorded coordinates.",
        "Pixel coordinates are fragile — re-record if the screen layout changes",
        "or if you move to a different display configuration.",
        '"""',
        "",
        "import time",
        "",
        "import pyautogui",
        "",
        "",
        "def main() -> None:",
    ]
    prev_ts: int | None = None
    for event in recording.events:
        if prev_ts is not None:
            gap_s = max(0.0, (event.ts_ms - prev_ts) / 1000.0)
            # Cap waits so overnight pauses don't ruin the replay.
            gap_s = min(gap_s, 3.0)
            if gap_s > 0.05:
                lines.append(f"    time.sleep({gap_s:.2f})")
        line = _desktop_event_line(event)
        if line is None:
            continue
        lines.append(f"    {line}")
        prev_ts = event.ts_ms
    lines.extend(
        [
            "",
            "",
            'if __name__ == "__main__":',
            "    main()",
            "",
        ]
    )
    return "\n".join(lines)


def _desktop_event_line(event: Event) -> str | None:
    if event.type == "click" and isinstance(event.value, dict):
        x, y = event.value.get("x", 0), event.value.get("y", 0)
        button = event.value.get("button", "left")
        if button not in ("left", "right", "middle"):
            button = "left"
        return f"pyautogui.click({x}, {y}, button={json.dumps(button)})"
    if event.type == "scroll" and isinstance(event.value, dict):
        dy = event.value.get("dy", 0)
        return f"pyautogui.scroll({dy})"
    if event.type == "input" and isinstance(event.value, str):
        return f"pyautogui.typewrite({json.dumps(event.value)}, interval=0.02)"
    if event.type == "key" and isinstance(event.value, dict):
        key = str(event.value.get("key", ""))
        if key and key.lower() not in {"shift", "ctrl", "alt", "cmd"}:
            return f"pyautogui.press({json.dumps(key)})"
    return None


def _best_selector(event: Event) -> str | None:
    """Pick the most stable selector available for this target."""
    alt = event.target.selector_alternatives
    return alt.testid or alt.aria or alt.css or alt.xpath or None
